export enum FilterMode {
    OFF,
    LOWPASS_12,
    LOWPASS_24,
    HIGHPASS_12,
    HIGHPASS_24,
    BANDPASS_12,
    BANDPASS_24,
    LOWPASS_STATE_VARIABLE,
    HIGHPASS_STATE_VARIABLE,
    BANDPASS_STATE_VARIABLE,
    NOTCH_STATE_VARIABLE,
    COUNT,
}
