export enum FloatId {
    Volume = 0,
    Morph,
    Duration,
    Frequency,
    envAmp1,
    envAmp1Time,
    envAmp2,
    envAmp2Time,
    envAmp3,
    envAmp3Time,
    envAmp4,
    envAmp4Time,
    envFreq1,
    envFreq1Time,
    envFreq2,
    envFreq2Time,
    envFreq3,
    envFreq3Time,
    envFreq4,
    envFreq4Time,
    filterCutoff,
    filterResonance,
    distortion,
    distortionRange,
}

export enum StringId {
    Wavetable = 0,
}
