export enum FloatId {
    Volume = 0,
    filterCutoff,
    filterResonance,
    filterMode,
    OscMorph,
    OscFrequency,
    OscAmplitude,
    envAttack,
    envDecay,
    envSustain,
    envRelease,
    envModAmplitude,
    envModPitch,
    envModMorph,
    envModCutoff,
    envModResonance,
    envModAmplitude2,
    envModPitch2,
    envModMorph2,
    envModMix,
    Osc2Morph,
    Osc2Frequency,
    Osc2Amplitude,
    osc2FreqNoteOn,
    Mix,
    osc2ModAmplitude,
    osc2ModPitch,
    osc2ModMorph,
    osc2ModCutOff,
    osc2ModResonance,
    osc2Active,
}

export enum StringId {
    oscWavetable = 0,
    osc2Wavetable,
}

export enum MOD_TARGET {
    MOD_TARGET_CUTOFF = 0,
    MOD_TARGET_RES,
    MOD_TARGET_PITCH,
    MOD_TARGET_AMP,
    MOD_TARGET_MORPH,
    MOD_TARGET_PITCH2,
    MOD_TARGET_AMP2,
    MOD_TARGET_MORPH2,
    MOD_TARGET_MIX,
    MOD_TARGET_COUNT,
}
